### ISSUE TITLE
Please let me use it.

### ISSUE THREAD

**Issue by asuka980810** [nondanee/nogimono#1]
https://nogimono.tk/

↑Please let me use it.

**Comment by nondanee** [comment]
Well, join this QQ group (480242179), and let me know who you are.

**Comment by nondanee** [comment]
This is the back-end manager for nogimono.
Only administrator have permission to login, so please let me know who you are.

I am sorry that there is no web front-end for users instead of an Android App.
You can download it here ↓
https://www.coolapk.com/apk/org.nogizaka46
The App is also open-sourced on Github ↓
https://github.com/minamihoshi/Nogimono
